# Generated by Django 5.0.4 on 2024-04-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorcredential',
            name='document_name',
            field=models.CharField(choices=[('ID', 'National ID'), ('CERT', 'Highest Certificate'), ('CV', 'Curriculum Vitae')], default='ID', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorcredential',
            name='document',
            field=models.FileField(upload_to='tutor_credentials/'),
        ),
    ]
