# Generated by Django 5.0.4 on 2024-04-19 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tutorcredential_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationstatus',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
