# Generated by Django 5.0.4 on 2024-04-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_verificationstatus_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationstatus',
            options={'verbose_name_plural': 'Verification Status'},
        ),
        migrations.AlterField(
            model_name='tutorcredential',
            name='document_name',
            field=models.CharField(choices=[('ID', 'National ID'), ('CERTIFICATE', 'Highest Certificate'), ('CV', 'Curriculum Vitae')], max_length=20),
        ),
    ]
