# Generated by Django 5.0.4 on 2024-04-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_verificationstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='specialized_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
