# Generated by Django 5.0.4 on 2024-04-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_tutor_specialized_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='experience_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='tutor',
            name='location',
            field=models.TextField(blank=True, help_text='city, state', null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='qualifications',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
