# Generated by Django 5.0.4 on 2024-04-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_tutor_experience_year_tutor_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorcredential',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
