# Generated by Django 5.0.4 on 2024-04-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_tutorcredential_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='qualifications',
            field=models.CharField(max_length=300),
        ),
    ]
