# Generated by Django 5.0.4 on 2024-04-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_tutor_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='location',
            field=models.CharField(blank=True, help_text='city, state', max_length=100, null=True),
        ),
    ]
