# Generated by Django 5.0.4 on 2024-04-22 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_verificationstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBook',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=20)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('ongoing', 'ongoing'), ('ended', 'ended')], max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tutor')),
            ],
        ),
    ]
