# Generated by Django 5.0.4 on 2024-04-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbook',
            name='additional_note',
            field=models.TextField(default='Hi'),
        ),
    ]
