# Generated by Django 5.0.4 on 2024-04-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_sessionbook_additional_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbook',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
