# Generated by Django 5.0.4 on 2024-04-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_alter_sessionbook_options_alter_sessionbook_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbook',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('ongoing', 'ongoing'), ('ended', 'ended')], default='pending', max_length=15),
        ),
    ]
