# Generated by Django 5.0.4 on 2024-04-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_alter_sessionbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbook',
            name='termination_reason',
            field=models.TextField(default='idk'),
        ),
        migrations.AlterField(
            model_name='sessionbook',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('ongoing', 'ongoing'), ('rejected', 'rejected'), ('ended', 'ended'), ('terminated', 'terminated')], default='pending', max_length=15),
        ),
    ]
